# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-12-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='abbr',
            field=models.TextField(blank=True, max_length=500, verbose_name='Сокращение'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='abbr',
            field=models.TextField(blank=True, max_length=500, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.TextField(blank=True, max_length=500, verbose_name='Название'),
        ),
    ]
