# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-12-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20201226_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='with_kpp_we',
            field=models.BooleanField(default=False, verbose_name='Проходит через КПП (выходные)'),
        ),
        migrations.AlterField(
            model_name='status',
            name='with_kpp',
            field=models.BooleanField(default=False, verbose_name='Проходит через КПП (будни)'),
        ),
    ]
