# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-12-26 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20201226_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforcontrol',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.City', verbose_name='Город'),
        ),
    ]
