# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-12-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20201226_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='with_comment',
            field=models.BooleanField(default=False, verbose_name='Требуется комментарий'),
        ),
    ]
