# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-01-02 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_auto_20210102_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='is_boss',
            field=models.BooleanField(default=False, verbose_name='Руководящая должность'),
        ),
    ]
