# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-01-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_userpost_name_boss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='category',
        ),
        migrations.AddField(
            model_name='userpost',
            name='is_duty',
            field=models.BooleanField(default=False, verbose_name='Дежурство'),
        ),
        migrations.DeleteModel(
            name='RankCategory',
        ),
    ]
