# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-01-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_auto_20210111_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforcontrol',
            name='is_gender',
            field=models.NullBooleanField(default=None, verbose_name='Военный'),
        ),
    ]
