# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-01-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0015_userforcontrol_is_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='signature',
            field=models.BooleanField(default=False, verbose_name='Заверение'),
        ),
    ]
