# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-01-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0016_usergroup_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата')),
                ('second_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('userForControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.UserForControl', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Вакцины',
                'verbose_name': 'Вакцина',
            },
        ),
    ]
