# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-01-22 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_vaccine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='date',
            new_name='first_date',
        ),
    ]
