# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-03-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0021_auto_20210225_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyByMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата создания')),
                ('policeman', models.IntegerField(blank=True, default=0, verbose_name='Дополнительный патруль')),
                ('patrol2', models.IntegerField(blank=True, default=0, verbose_name='Комендатура')),
            ],
            options={
                'verbose_name': 'Наряды с доп. информацией',
                'verbose_name_plural': 'Наряды с доп. информацией',
            },
        ),
    ]
