# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-03-09 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_dutybymonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип звания',
                'verbose_name_plural': 'Типы званий',
            },
        ),
        migrations.RemoveField(
            model_name='rank',
            name='is_old',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='is_small',
        ),
        migrations.AddField(
            model_name='rank',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.TypeRank', verbose_name='Тип звания'),
        ),
    ]
