# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2021-03-12 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0023_auto_20210309_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutybymonth',
            name='patrol2_skip',
            field=models.TextField(blank=True, default='[]', verbose_name='Комендатура  для пропуска в месяц'),
        ),
        migrations.AddField(
            model_name='dutybymonth',
            name='policeman_skip',
            field=models.TextField(blank=True, default='[]', verbose_name='Дополнительный патруль для пропуска в месяц'),
        ),
    ]
