# Generated by Django 3.2.4 on 2021-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0026_auto_20210611_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforcontrol',
            name='is_gender',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Военный'),
        ),
    ]
