# Generated by Django 3.2.4 on 2021-06-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0027_alter_userforcontrol_is_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.usergroup', verbose_name='Подразделение пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Телефон'),
        ),
    ]
