# Generated by Django 3.2.4 on 2021-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0029_profile_false_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='false_user',
        ),
        migrations.AddField(
            model_name='userforcontrol',
            name='email',
            field=models.TextField(blank=True, max_length=500, verbose_name='Email'),
        ),
    ]
