# Generated by Django 3.2.4 on 2021-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0030_auto_20210623_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='Guest'),
        ),
    ]
