# Generated by Django 3.2.4 on 2021-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0031_profile_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_duty',
            field=models.BooleanField(default=False, verbose_name='Duty'),
        ),
    ]
