# Generated by Django 3.2.4 on 2021-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0032_profile_is_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydata',
            name='manual',
            field=models.BooleanField(default=True),
        ),
    ]
