# Generated by Django 3.2.4 on 2021-07-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0033_daydata_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antitela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('userForControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.userforcontrol', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Антитела',
                'verbose_name_plural': 'Антитела',
            },
        ),
    ]
