# Generated by Django 3.2.4 on 2021-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0035_auto_20210713_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='antitela',
            name='comment2',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='antitela',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Номер справки'),
        ),
    ]
