# Generated by Django 3.2.4 on 2021-07-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0036_auto_20210714_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_duty_control',
            field=models.BooleanField(default=False, verbose_name='DutyControl'),
        ),
    ]
