# Generated by Django 3.2.4 on 2021-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0036_auto_20210714_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='name_in_ldap',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
