# Generated by Django 3.2.4 on 2021-07-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0038_merge_20210715_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, verbose_name='Название')),
                ('name_in_ldap', models.TextField(blank=True, max_length=500, verbose_name='Название в AD')),
                ('page', models.TextField(blank=True, max_length=500, verbose_name='Страница')),
                ('is_edit', models.BooleanField(default=True, verbose_name='Редактирование')),
            ],
            options={
                'verbose_name': 'Тип профиля пользователя',
                'verbose_name_plural': 'Типы профилей пользователей',
            },
        ),
        migrations.CreateModel(
            name='ProfileTypeSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.profile', verbose_name='Профиль пользователя')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.profiletype', verbose_name='Тип профиля пользователя')),
            ],
            options={
                'verbose_name': 'Тип профиля пользователя',
                'verbose_name_plural': 'Типы профилей пользователей',
            },
        ),
    ]
