# Generated by Django 3.2.4 on 2021-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0039_profiletype_profiletypeselect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletype',
            name='is_edit',
        ),
        migrations.AddField(
            model_name='profiletype',
            name='action',
            field=models.CharField(blank=True, max_length=200, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='name_in_ldap',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название в AD'),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='page',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страница'),
        ),
    ]
