# Generated by Django 3.2.4 on 2021-07-21 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0040_auto_20210716_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_for_control',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.userforcontrol', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_for_work',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.profile', verbose_name='Делегирование'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
