# Generated by Django 3.2.4 on 2021-07-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0041_auto_20210721_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_for_work',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.profile', verbose_name='Делегирование'),
        ),
    ]
