# Generated by Django 3.2.4 on 2021-08-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0043_profiletype_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletype',
            name='is_default',
        ),
    ]
