# Generated by Django 3.2.4 on 2021-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0044_remove_profiletype_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='countComponent',
            field=models.IntegerField(blank=True, default=2, verbose_name='Компоненты'),
        ),
    ]
