# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-21 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, verbose_name=' Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'л/с по дням',
                'verbose_name_plural': 'л/с по дням',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, max_length=500, verbose_name='Телефон')),
                ('is_control', models.BooleanField(default=False, verbose_name='Контролирующий')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователей',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, verbose_name=' Название')),
            ],
            options={
                'verbose_name': 'Причина отсутствия',
                'verbose_name_plural': 'Причины отсутствия',
            },
        ),
        migrations.CreateModel(
            name='UserForControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, verbose_name='ФИО')),
                ('rank', models.TextField(blank=True, max_length=500, verbose_name='Воиское звание')),
                ('is_military', models.BooleanField(default=True, verbose_name='Военный')),
                ('is_woman_with_children', models.BooleanField(default=False, verbose_name='Женщина с детьми')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'л/с по подразделениям',
                'verbose_name_plural': 'л/с по подразделениям',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Подразделение пользователей',
                'verbose_name_plural': 'Подразделение пользователей',
            },
        ),
        migrations.AddField(
            model_name='userforcontrol',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.UserGroup', verbose_name='Подразделение пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.UserGroup', verbose_name='Подразделение пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='daydata',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.Status', verbose_name='Причина отсутствия'),
        ),
        migrations.AddField(
            model_name='daydata',
            name='userForControl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.UserForControl', verbose_name='Пользователь'),
        ),
    ]
