# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, verbose_name=' Название')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.AlterField(
            model_name='userforcontrol',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Rank', verbose_name='Звание'),
        ),
    ]
