# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20201024_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforcontrol',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.Rank', verbose_name='Звание'),
        ),
    ]
