# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20201024_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.UserGroup', verbose_name='Подразделение пользователя'),
        ),
    ]
