# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_usergroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='abbr',
            field=models.TextField(blank=True, max_length=500, verbose_name=' Сокращение'),
        ),
    ]
