# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_status_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
