# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-01 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_usergroup_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='position',
            field=models.FloatField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
