# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_auto_20201101_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.UserGroup', verbose_name='Подразделение'),
        ),
    ]
