# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20201105_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daydata',
            name='bodyTemperature',
        ),
        migrations.RemoveField(
            model_name='daydata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_required',
        ),
        migrations.AddField(
            model_name='status',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.Status', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='daydata',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
