# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_auto_20201105_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='extraDataForDayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Дополнительное поле для статуса',
                'verbose_name_plural': 'Дополнительные поля для статуса',
            },
        ),
        migrations.AlterField(
            model_name='daydata',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='extradatafordaydata',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.DayData', verbose_name='DayData'),
        ),
        migrations.AddField(
            model_name='extradatafordaydata',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Site.Status', verbose_name='Название'),
        ),
    ]
